# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greetpb/greet.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='greetpb/greet.proto',
  package='greet',
  syntax='proto3',
  serialized_options=b'\n\020com.mesadhan.gpsP\001Z\t./greetpb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13greetpb/greet.proto\x12\x05greet\"1\n\x08Greeting\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\"1\n\x0cGreetRequest\x12!\n\x08greeting\x18\x01 \x01(\x0b\x32\x0f.greet.Greeting\"\x1f\n\rGreetResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\":\n\x15GreetManyTimesRequest\x12!\n\x08greeting\x18\x01 \x01(\x0b\x32\x0f.greet.Greeting\"(\n\x16GreetManyTimesResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"5\n\x10LongGreetRequest\x12!\n\x08greeting\x18\x01 \x01(\x0b\x32\x0f.greet.Greeting\"#\n\x11LongGreetResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"9\n\x14GreetEveryoneRequest\x12!\n\x08greeting\x18\x01 \x01(\x0b\x32\x0f.greet.Greeting\"\'\n\x15GreetEveryoneResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2\xb9\x02\n\x0cGreetService\x12\x34\n\x05Greet\x12\x13.greet.GreetRequest\x1a\x14.greet.GreetResponse\"\x00\x12W\n\x14GreetManyTimesMethod\x12\x1c.greet.GreetManyTimesRequest\x1a\x1d.greet.GreetManyTimesResponse\"\x00\x30\x01\x12\x42\n\tLongGreet\x12\x17.greet.LongGreetRequest\x1a\x18.greet.LongGreetResponse\"\x00(\x01\x12V\n\x13GreetEveryoneMethod\x12\x1b.greet.GreetEveryoneRequest\x1a\x1c.greet.GreetEveryoneResponse\"\x00(\x01\x30\x01\x42\x1f\n\x10\x63om.mesadhan.gpsP\x01Z\t./greetpbb\x06proto3'
)




_GREETING = _descriptor.Descriptor(
  name='Greeting',
  full_name='greet.Greeting',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='first_name', full_name='greet.Greeting.first_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='greet.Greeting.last_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=79,
)


_GREETREQUEST = _descriptor.Descriptor(
  name='GreetRequest',
  full_name='greet.GreetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='greeting', full_name='greet.GreetRequest.greeting', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=130,
)


_GREETRESPONSE = _descriptor.Descriptor(
  name='GreetResponse',
  full_name='greet.GreetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='greet.GreetResponse.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=163,
)


_GREETMANYTIMESREQUEST = _descriptor.Descriptor(
  name='GreetManyTimesRequest',
  full_name='greet.GreetManyTimesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='greeting', full_name='greet.GreetManyTimesRequest.greeting', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=223,
)


_GREETMANYTIMESRESPONSE = _descriptor.Descriptor(
  name='GreetManyTimesResponse',
  full_name='greet.GreetManyTimesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='greet.GreetManyTimesResponse.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=265,
)


_LONGGREETREQUEST = _descriptor.Descriptor(
  name='LongGreetRequest',
  full_name='greet.LongGreetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='greeting', full_name='greet.LongGreetRequest.greeting', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=320,
)


_LONGGREETRESPONSE = _descriptor.Descriptor(
  name='LongGreetResponse',
  full_name='greet.LongGreetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='greet.LongGreetResponse.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=322,
  serialized_end=357,
)


_GREETEVERYONEREQUEST = _descriptor.Descriptor(
  name='GreetEveryoneRequest',
  full_name='greet.GreetEveryoneRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='greeting', full_name='greet.GreetEveryoneRequest.greeting', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=359,
  serialized_end=416,
)


_GREETEVERYONERESPONSE = _descriptor.Descriptor(
  name='GreetEveryoneResponse',
  full_name='greet.GreetEveryoneResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='greet.GreetEveryoneResponse.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=418,
  serialized_end=457,
)

_GREETREQUEST.fields_by_name['greeting'].message_type = _GREETING
_GREETMANYTIMESREQUEST.fields_by_name['greeting'].message_type = _GREETING
_LONGGREETREQUEST.fields_by_name['greeting'].message_type = _GREETING
_GREETEVERYONEREQUEST.fields_by_name['greeting'].message_type = _GREETING
DESCRIPTOR.message_types_by_name['Greeting'] = _GREETING
DESCRIPTOR.message_types_by_name['GreetRequest'] = _GREETREQUEST
DESCRIPTOR.message_types_by_name['GreetResponse'] = _GREETRESPONSE
DESCRIPTOR.message_types_by_name['GreetManyTimesRequest'] = _GREETMANYTIMESREQUEST
DESCRIPTOR.message_types_by_name['GreetManyTimesResponse'] = _GREETMANYTIMESRESPONSE
DESCRIPTOR.message_types_by_name['LongGreetRequest'] = _LONGGREETREQUEST
DESCRIPTOR.message_types_by_name['LongGreetResponse'] = _LONGGREETRESPONSE
DESCRIPTOR.message_types_by_name['GreetEveryoneRequest'] = _GREETEVERYONEREQUEST
DESCRIPTOR.message_types_by_name['GreetEveryoneResponse'] = _GREETEVERYONERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Greeting = _reflection.GeneratedProtocolMessageType('Greeting', (_message.Message,), {
  'DESCRIPTOR' : _GREETING,
  '__module__' : 'greetpb.greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.Greeting)
  })
_sym_db.RegisterMessage(Greeting)

GreetRequest = _reflection.GeneratedProtocolMessageType('GreetRequest', (_message.Message,), {
  'DESCRIPTOR' : _GREETREQUEST,
  '__module__' : 'greetpb.greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.GreetRequest)
  })
_sym_db.RegisterMessage(GreetRequest)

GreetResponse = _reflection.GeneratedProtocolMessageType('GreetResponse', (_message.Message,), {
  'DESCRIPTOR' : _GREETRESPONSE,
  '__module__' : 'greetpb.greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.GreetResponse)
  })
_sym_db.RegisterMessage(GreetResponse)

GreetManyTimesRequest = _reflection.GeneratedProtocolMessageType('GreetManyTimesRequest', (_message.Message,), {
  'DESCRIPTOR' : _GREETMANYTIMESREQUEST,
  '__module__' : 'greetpb.greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.GreetManyTimesRequest)
  })
_sym_db.RegisterMessage(GreetManyTimesRequest)

GreetManyTimesResponse = _reflection.GeneratedProtocolMessageType('GreetManyTimesResponse', (_message.Message,), {
  'DESCRIPTOR' : _GREETMANYTIMESRESPONSE,
  '__module__' : 'greetpb.greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.GreetManyTimesResponse)
  })
_sym_db.RegisterMessage(GreetManyTimesResponse)

LongGreetRequest = _reflection.GeneratedProtocolMessageType('LongGreetRequest', (_message.Message,), {
  'DESCRIPTOR' : _LONGGREETREQUEST,
  '__module__' : 'greetpb.greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.LongGreetRequest)
  })
_sym_db.RegisterMessage(LongGreetRequest)

LongGreetResponse = _reflection.GeneratedProtocolMessageType('LongGreetResponse', (_message.Message,), {
  'DESCRIPTOR' : _LONGGREETRESPONSE,
  '__module__' : 'greetpb.greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.LongGreetResponse)
  })
_sym_db.RegisterMessage(LongGreetResponse)

GreetEveryoneRequest = _reflection.GeneratedProtocolMessageType('GreetEveryoneRequest', (_message.Message,), {
  'DESCRIPTOR' : _GREETEVERYONEREQUEST,
  '__module__' : 'greetpb.greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.GreetEveryoneRequest)
  })
_sym_db.RegisterMessage(GreetEveryoneRequest)

GreetEveryoneResponse = _reflection.GeneratedProtocolMessageType('GreetEveryoneResponse', (_message.Message,), {
  'DESCRIPTOR' : _GREETEVERYONERESPONSE,
  '__module__' : 'greetpb.greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.GreetEveryoneResponse)
  })
_sym_db.RegisterMessage(GreetEveryoneResponse)


DESCRIPTOR._options = None

_GREETSERVICE = _descriptor.ServiceDescriptor(
  name='GreetService',
  full_name='greet.GreetService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=460,
  serialized_end=773,
  methods=[
  _descriptor.MethodDescriptor(
    name='Greet',
    full_name='greet.GreetService.Greet',
    index=0,
    containing_service=None,
    input_type=_GREETREQUEST,
    output_type=_GREETRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GreetManyTimesMethod',
    full_name='greet.GreetService.GreetManyTimesMethod',
    index=1,
    containing_service=None,
    input_type=_GREETMANYTIMESREQUEST,
    output_type=_GREETMANYTIMESRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='LongGreet',
    full_name='greet.GreetService.LongGreet',
    index=2,
    containing_service=None,
    input_type=_LONGGREETREQUEST,
    output_type=_LONGGREETRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GreetEveryoneMethod',
    full_name='greet.GreetService.GreetEveryoneMethod',
    index=3,
    containing_service=None,
    input_type=_GREETEVERYONEREQUEST,
    output_type=_GREETEVERYONERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETSERVICE)

DESCRIPTOR.services_by_name['GreetService'] = _GREETSERVICE

# @@protoc_insertion_point(module_scope)
